ori_AP<-read.csv('.\\Autophagy.csv',row.names = 1)
gene_AP<-data.frame(ori_AP[,1:30])
pca_AP<-prcomp(gene_AP,center = F,scale. = F)
summary(pca_AP)
PC_AP<-data.frame(pca_AP$x)
#
ori_P<-read.csv('.\\Pyroptosis.csv',row.names = 1)
gene_P<-data.frame(ori_P[,1:28])
pca_P<-prcomp(gene_P,center = F,scale. = F)
summary(pca_P)
PC_P<-data.frame(pca_P$x)
#
ori_A<-read.csv('.\\Apoptosis.csv',row.names = 1)
gene_A<-data.frame(ori_A[,1:132])
pca_A<-prcomp(gene_A,center = F,scale. = F)
summary(pca_A)
PC_A<-data.frame(pca_A$x)
#
ori_N<-read.csv('.\\Necroptosis.csv',row.names = 1)
gene_N<-data.frame(ori_N[,1:29])
pca_N<-prcomp(gene_N,center = F,scale. = F)
summary(pca_N)
PC_N<-data.frame(pca_N$x)
#
ori_C<-read.csv('.\\Cuproptosis.csv',row.names = 1)
gene_C<-data.frame(ori_C[,1:10])
pca_C<-prcomp(gene_C,center = F,scale. = F)
summary(pca_C)
PC_C<-data.frame(pca_C$x)
#
Celldeath_feature<-cbind(-PC_AP$PC1,-PC_P$PC1,-PC_A$PC1,-PC_N$PC1,-PC_F$PC1,ori_A$status,ori_A$os)
colnames(Celldeath_feature)<-c('Autophagy','Pyroptosis','Apoptosis','Necroptosis','Cuproptosis','status','os')
rownames(Celldeath_feature)<-rownames(ori_A)
Celldeath_feature<-as.data.frame(Celldeath_feature)
cli<-read.csv('.\\clinical.csv',row.names = 1)
Celldeath_feature$id<-rownames(Celldeath_feature)
Celldeath_feature$id<-substr(Celldeath_feature$id,1,12)
Celldeath_feature$id<-gsub('.','-',Celldeath_feature$id,fixed = T,)
library(dplyr)
Celldeath_feature<-left_join(Celldeath_feature,cli,by='id')
rownames(Celldeath_feature)<-rownames(loading_P)
Celldeath_feature<-Celldeath_feature[,-8]
write.csv(Celldeath_feature,file = '.\\Celldeath_feature.csv')
#
library(factoextra)
library(ggpubr)
C1<-fviz_eig(pca_AP, addlabels = TRUE,ncp = 5, ylim = c(0, 100))
C2<-fviz_contrib(pca_AP, choice = "var", axes = 1, top = 10)
C<-ggarrange(C1,C2,ncol = 2)
ggsave('Autophagy.tiff',plot = C1,width = 6,height = 4,dpi = 300)
